# Generated by Django 5.0.1 on 2024-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_ordermodel_options_alter_paymentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
