# Generated by Django 5.0.1 on 2024-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='states',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
