# Generated by Django 5.0.1 on 2024-03-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount if applicable', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.state'),
        ),
    ]
