# Generated by Django 5.0.1 on 2024-03-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_state_productmodel_discount_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('boolean_value', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.statemodel'),
        ),
    ]
