# Generated by Django 5.0.1 on 2024-03-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_statemodel_delete_state_alter_productmodel_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemodel',
            name='boolean_value',
        ),
        migrations.RemoveField(
            model_name='statemodel',
            name='number_value',
        ),
    ]
